import {
  HandLandmarker,
  FilesetResolver,
} from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14";
import {
  CUSTOM_PROMPT_MAX_LENGTH,
  DEFAULT_STYLE_ID,
  STYLE_PRESETS,
  buildGenerationPrompt,
  getStylePreset,
} from "./prompt-builder.js";
import { buildGeminiInteractionBody } from "./gemini-request.js";
import { GENERATION_CAPABILITIES } from "./generation-capabilities.js";
import {
  ReferenceImageSelection,
  buildReferenceImageView,
  referenceImageCapabilityState,
  validateReferenceImage,
} from "./reference-image.js";
import { StabilizedFrameTracker } from "./tracking.js";
import { PerspectiveCanvasCompositor } from "./compositing.js";
import {
  PORTAL_CROSSING_CONFIG,
  PortalCrossingController,
  TransitionState,
} from "./portal-crossing.js";
import { DIRECTOR_MODEL, buildDirectorRequest, extractDirectorText } from "./director.js";
import {
  WORKFLOW_STAGES,
  nextWorkflowState,
  validateVideoFile,
  validateVideoMetadata,
  workflowView,
} from "./workflow.js";

const WASM_URL =
  "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm";
const MODEL_URL =
  "https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task";

const GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta";
const WRIST = 0, THUMB_TIP = 4, INDEX_TIP = 8, MIDDLE_MCP = 9;

// Tracking constants — same audited pipeline as the live web app.
const MAX_LOST_FRAMES = 25;
const JUMP_CONFIRM_FRAMES = 2;
const developmentParams = new URLSearchParams(window.location.search);
const TRACKING_MODE = developmentParams.get("tracking") === "legacy"
  ? "legacy"
  : "stabilized";
const requestedCompositingMode = developmentParams.get("compositing");
const COMPOSITING_MODE = requestedCompositingMode === "legacy" ? "legacy" :
  requestedCompositingMode === "perspective" ? "perspective" : "perspective_occlusion";
const PORTAL_MODE = developmentParams.get("portal") === "only" ? "portal_only" : "portal_crossing";
const PARALLAX_ENABLED = developmentParams.get("parallax") !== "off";
let portalCrossingEnabled = PORTAL_MODE === "portal_crossing" && localStorage.getItem("portal-crossing") !== "off";
let parallaxEnabled = PARALLAX_ENABLED && localStorage.getItem("portal-parallax") !== "off";
const forcedTransitionParameter = developmentParams.get("transitionProgress");
const forcedTransitionValue = Number(forcedTransitionParameter);
const FORCED_TRANSITION_PROGRESS = forcedTransitionParameter !== null && Number.isFinite(forcedTransitionValue)
  ? Math.max(0, Math.min(1, forcedTransitionValue))
  : null;

const orig = document.getElementById("orig");
const sty = document.getElementById("sty");
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
const statusEl = document.getElementById("status");
const stage = document.getElementById("stage");
const drop = document.getElementById("drop");
const btnGenerate = document.getElementById("btn-generate");
const btnPlaceholder = document.getElementById("btn-placeholder");
const btnPlay = document.getElementById("btn-play");
const btnExport = document.getElementById("btn-export");
const btnCancel = document.getElementById("btn-cancel");
const btnReset = document.getElementById("btn-reset");
const btnDirector = document.getElementById("btn-director");
const directorStatus = document.getElementById("director-status");
const originalPreview = document.getElementById("original-preview");
const progressPanel = document.getElementById("progress-panel");
const progressFill = document.getElementById("progress-fill");
const progressLabel = document.getElementById("progress-label");
const portalCrossingToggle = document.getElementById("portal-crossing-toggle");
const parallaxToggle = document.getElementById("parallax-toggle");
const fileInput = document.getElementById("file");

let landmarker = null;
let videoFile = null;
let haveAI = false;        // stylized video generated by Gemini
let usePlaceholder = false; // hue-shift stand-in for keyless testing
let corners = null;
let presence = 0;
let frameActive = false;
let lostFrames = 0;
let jumpFrames = 0;
let stabilizedTracker = null;
let trackerState = null;
let perspectiveCompositor = null;
let portalCrossingController = null;
let portalTransition = Object.freeze({
  state: TransitionState.INACTIVE,
  coverage: 0,
  progress: 0,
  confidence: 0,
  expandedQuad: null,
  portalId: null,
});
let currentHands = [];
let recorder = null;
let exporting = false;
let generationAbortController = null;
let sourceObjectUrl = null;
let stylizedObjectUrl = null;
let exportObjectUrl = null;
let workflowState = "empty";
let activeWorkflowStage = null;

function updateWorkflow(event) {
  workflowState = nextWorkflowState(workflowState, event);
  const view = workflowView(workflowState, !!videoFile, haveAI || usePlaceholder);
  btnGenerate.disabled = !view.canGenerate;
  btnPlaceholder.disabled = !view.canGenerate;
  btnPlay.disabled = !view.canPreview;
  btnExport.disabled = !view.canExport;
  btnCancel.classList.toggle("hidden", !view.canCancel);
}

function revokeUrl(name) {
  const value = name === "source" ? sourceObjectUrl : name === "stylized" ? stylizedObjectUrl : exportObjectUrl;
  if (value) URL.revokeObjectURL(value);
  if (name === "source") sourceObjectUrl = null;
  else if (name === "stylized") stylizedObjectUrl = null;
  else exportObjectUrl = null;
}

function stopMedia() {
  orig.pause();
  sty.pause();
  if (recorder?.state === "recording") recorder.stop();
  recorder = null;
  exporting = false;
}

function status(msg) {
  statusEl.textContent = msg;
  // Messages ending in an ellipsis are in-progress — show the spinner.
  statusEl.classList.toggle("working", /…\s*$/.test(msg));
}

function setWorkflowStage(stageName, detail = "") {
  const index = WORKFLOW_STAGES.indexOf(stageName);
  activeWorkflowStage = index < 0 ? null : stageName;
  progressPanel.classList.toggle("hidden", index < 0);
  if (index < 0) return;
  progressFill.style.width = `${((index + 1) / WORKFLOW_STAGES.length) * 100}%`;
  progressLabel.textContent = detail ? `${stageName} — ${detail}` : stageName;
}

function clearWorkflowStage() {
  activeWorkflowStage = null;
  progressPanel.classList.add("hidden");
  progressFill.style.width = "0";
  progressLabel.textContent = "";
}

function friendlyGenerationError(error, hasReference) {
  const detail = String(error?.message || error);
  if (/404|403|region|location|not available|not found/i.test(detail)) {
    return "This Gemini video model is not available for the current key or region.";
  }
  if (hasReference) return `Reference-image generation failed: ${detail}`;
  if (activeWorkflowStage === "Uploading media") return `Gemini upload failed: ${detail}`;
  return `Gemini generation failed: ${detail}`;
}

// ---- key + style panel ----
const keyInput = document.getElementById("gem-key");
const keyRemember = document.getElementById("gem-remember");
const styleSelect = document.getElementById("style-select");
const styleCustom = document.getElementById("style-custom");
const styleDescription = document.getElementById("style-description");
const promptRequirement = document.getElementById("prompt-requirement");
const promptValidation = document.getElementById("prompt-validation");
const promptCount = document.getElementById("prompt-count");
const referenceImageInput = document.getElementById("reference-image");
const referenceImageChoose = document.getElementById("reference-image-choose");
const referenceImagePreview = document.getElementById("reference-image-preview");
const referenceImageThumbnail = document.getElementById("reference-image-thumbnail");
const referenceImageMetadata = document.getElementById("reference-image-metadata");
const referenceImageRemove = document.getElementById("reference-image-remove");
const referenceImageError = document.getElementById("reference-image-error");
const referenceCapabilityReason = document.getElementById("reference-capability-reason");
const referenceImageSelection = new ReferenceImageSelection();

keyInput.value =
  localStorage.getItem("gemini-key") || sessionStorage.getItem("gemini-key") || "";
keyRemember.checked = !!localStorage.getItem("gemini-key");
STYLE_PRESETS.forEach((preset) => {
  const option = document.createElement("option");
  option.value = preset.id;
  option.textContent = preset.label;
  styleSelect.append(option);
});
const storedStyle = localStorage.getItem("ai-style");
styleSelect.value = getStylePreset(storedStyle) ? storedStyle : DEFAULT_STYLE_ID;
styleCustom.value = localStorage.getItem("ai-style-custom") || "";
styleCustom.maxLength = CUSTOM_PROMPT_MAX_LENGTH;

function clearPromptValidation() {
  promptValidation.textContent = "";
  styleCustom.removeAttribute("aria-invalid");
}

function updatePromptFields() {
  const preset = getStylePreset(styleSelect.value);
  const customRequired = preset?.id === "custom";
  styleDescription.textContent = preset?.description || "";
  promptRequirement.textContent = customRequired ? "required" : "optional";
  styleCustom.required = customRequired;
  styleCustom.placeholder = customRequired
    ? "Describe the transformation you want."
    : "Optional — describe what you want the scene to become.";
  promptCount.textContent = `${styleCustom.value.length}/${CUSTOM_PROMPT_MAX_LENGTH}`;
  clearPromptValidation();
}

function currentGenerationPrompt() {
  return buildGenerationPrompt({
    stylePresetId: styleSelect.value,
    customPrompt: styleCustom.value,
    hasReferenceImage: !!referenceImageSelection.file,
  });
}

function currentGenerationIntent() {
  const metadata = referenceImageSelection.metadata;
  return Object.freeze({
    stylePresetId: styleSelect.value,
    customPrompt: styleCustom.value,
    referenceImage: metadata
      ? Object.freeze({
          name: metadata.name,
          mimeType: metadata.mimeType,
          size: metadata.size,
          width: metadata.width,
          height: metadata.height,
        })
      : null,
  });
}

function referenceDebugMetadata() {
  const metadata = referenceImageSelection.metadata;
  return Object.freeze({
    selectedStyleId: styleSelect.value,
    customPromptPresent: !!styleCustom.value.trim(),
    referenceImagePresent: !!metadata,
    referenceMime: metadata?.mimeType || null,
    referenceDimensions: metadata
      ? Object.freeze({ width: metadata.width, height: metadata.height })
      : null,
    builtPrompt: currentGenerationPrompt(),
    providerCapability: GENERATION_CAPABILITIES,
  });
}

styleSelect.addEventListener("change", () => {
  localStorage.setItem("ai-style", styleSelect.value);
  updatePromptFields();
});
styleCustom.addEventListener("input", () => {
  localStorage.setItem("ai-style-custom", styleCustom.value);
  updatePromptFields();
});
updatePromptFields();

portalCrossingToggle.checked = portalCrossingEnabled;
parallaxToggle.checked = parallaxEnabled;
portalCrossingToggle.addEventListener("change", () => {
  portalCrossingEnabled = portalCrossingToggle.checked;
  localStorage.setItem("portal-crossing", portalCrossingEnabled ? "on" : "off");
  if (canvas.width && canvas.height) resetTracking();
});
parallaxToggle.addEventListener("change", () => {
  parallaxEnabled = parallaxToggle.checked;
  localStorage.setItem("portal-parallax", parallaxEnabled ? "on" : "off");
  if (canvas.width && canvas.height) resetTracking();
});

btnDirector.addEventListener("click", async () => {
  const key = saveKey();
  if (!key) {
    directorStatus.textContent = "Add your Gemini key to use Director assist.";
    keyInput.focus();
    return;
  }
  btnDirector.disabled = true;
  directorStatus.textContent = "Enhancing your direction…";
  setWorkflowStage("Preparing generation", "Director assist");
  try {
    const preset = getStylePreset(styleSelect.value);
    const response = await gemFetch(key, `models/${DIRECTOR_MODEL}:generateContent`, {
      method: "POST",
      body: JSON.stringify(buildDirectorRequest({
        styleLabel: preset?.label || "Custom",
        userPrompt: styleCustom.value,
        hasReferenceImage: !!referenceImageSelection.file,
      })),
    });
    styleCustom.value = extractDirectorText(response);
    localStorage.setItem("ai-style-custom", styleCustom.value);
    updatePromptFields();
    directorStatus.textContent = "Director draft added — review and edit it before generation.";
    styleCustom.focus();
  } catch (error) {
    console.error("Director assist failed", error);
    directorStatus.textContent = `Director assist failed: ${error.message || error}`;
  } finally {
    btnDirector.disabled = false;
    clearWorkflowStage();
  }
});

function renderReferenceImage() {
  const view = buildReferenceImageView(referenceImageSelection);
  referenceImagePreview.classList.toggle("hidden", !view.previewVisible);
  referenceImageChoose.classList.toggle("hidden", !view.chooseVisible);
  if (view.previewVisible) {
    referenceImageThumbnail.src = view.previewUrl;
    referenceImageMetadata.textContent = view.metadataText;
  } else {
    referenceImageThumbnail.removeAttribute("src");
    referenceImageMetadata.textContent = "";
  }
}

referenceImageInput.addEventListener("change", async () => {
  const file = referenceImageInput.files?.[0];
  if (!file) return;
  referenceImageError.textContent = "";
  try {
    const metadata = await validateReferenceImage(file);
    referenceImageSelection.replace(file, metadata);
    renderReferenceImage();
  } catch (error) {
    referenceImageInput.value = "";
    referenceImageError.textContent = error.message || String(error);
  }
});
referenceImageRemove.addEventListener("click", () => {
  referenceImageSelection.clear();
  referenceImageInput.value = "";
  referenceImageError.textContent = "";
  renderReferenceImage();
});
window.addEventListener("beforeunload", () => {
  referenceImageSelection.clear();
  revokeUrl("source");
  revokeUrl("stylized");
  revokeUrl("export");
});

const referenceCapability = referenceImageCapabilityState(GENERATION_CAPABILITIES);
if (!referenceCapability.enabled) {
  referenceImageInput.disabled = true;
  referenceImageChoose.setAttribute("aria-disabled", "true");
  referenceImageChoose.classList.add("hidden");
  referenceCapabilityReason.textContent = referenceCapability.reason;
  referenceCapabilityReason.classList.remove("hidden");
}

// Developer hook: inspect the final pure prompt without an API request.
window.__fingerFrameDebug = Object.freeze({
  buildPrompt: currentGenerationPrompt,
  presets: STYLE_PRESETS.map(({ id, label }) => ({ id, label })),
  trackingMode: TRACKING_MODE,
  trackingState: () => trackerState,
  compositingMode: COMPOSITING_MODE,
  generationIntent: currentGenerationIntent,
  generationMetadata: referenceDebugMetadata,
  generationCapabilities: GENERATION_CAPABILITIES,
  portalMode: () => portalCrossingEnabled ? "portal_crossing" : "portal_only",
  parallaxEnabled: () => parallaxEnabled,
  portalCrossingConfig: PORTAL_CROSSING_CONFIG,
  transitionState: () => portalTransition,
  portalEvents: () => portalCrossingController?.eventMetadata() || [],
});

function saveKey() {
  const key = keyInput.value.trim();
  localStorage.removeItem("gemini-key");
  sessionStorage.removeItem("gemini-key");
  if (key) (keyRemember.checked ? localStorage : sessionStorage).setItem("gemini-key", key);
  return key;
}

// ---- video loading ----
fileInput.addEventListener("change", (e) => {
  if (e.target.files[0]) loadVideo(e.target.files[0]);
});
drop.addEventListener("dragover", (e) => {
  e.preventDefault();
  drop.classList.add("over");
});
drop.addEventListener("dragleave", () => drop.classList.remove("over"));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  drop.classList.remove("over");
  if (e.dataTransfer.files[0]) loadVideo(e.dataTransfer.files[0]);
});

async function loadVideo(file) {
  stopMedia();
  generationAbortController?.abort();
  clearWorkflowStage();
  try {
    validateVideoFile(file);
    setWorkflowStage("Analyzing video");
    status("Analyzing video…");
    revokeUrl("source");
    revokeUrl("stylized");
    sourceObjectUrl = URL.createObjectURL(file);
    orig.src = sourceObjectUrl;
    originalPreview.src = sourceObjectUrl;
    await waitForMetadata(orig, "The browser could not decode this video.");
    validateVideoMetadata({
      duration: orig.duration,
      width: orig.videoWidth,
      height: orig.videoHeight,
    });
    videoFile = file;
    haveAI = false;
    usePlaceholder = false;
    canvas.width = orig.videoWidth;
    canvas.height = orig.videoHeight;
    resetTracking();
    stage.style.display = "flex";
    drop.classList.add("compact");
    drawPoster();
    updateWorkflow("video_loaded");
    clearWorkflowStage();
    status(
      `Loaded ${file.name} (${orig.videoWidth}×${orig.videoHeight}, ` +
      `${orig.duration.toFixed(1)}s). Choose a look, then generate.`
    );
    if (!landmarker) initLandmarker().catch((error) => {
      console.error("Tracking initialization failed", error);
      status("Tracking could not start. Check your connection and reload the page.");
    });
  } catch (error) {
    console.error("Video load failed", error);
    revokeUrl("source");
    videoFile = null;
    fileInput.value = "";
    updateWorkflow("reset");
    clearWorkflowStage();
    status(`Video unavailable: ${error.message || error}`);
  }
}

function waitForMetadata(video, message) {
  return new Promise((resolve, reject) => {
    const cleanup = () => {
      video.removeEventListener("loadedmetadata", loaded);
      video.removeEventListener("error", failed);
    };
    const loaded = () => { cleanup(); resolve(); };
    const failed = () => { cleanup(); reject(new Error(message)); };
    video.addEventListener("loadedmetadata", loaded, { once: true });
    video.addEventListener("error", failed, { once: true });
  });
}

function resetProject() {
  generationAbortController?.abort();
  generationAbortController = null;
  stopMedia();
  revokeUrl("source");
  revokeUrl("stylized");
  revokeUrl("export");
  videoFile = null;
  haveAI = false;
  usePlaceholder = false;
  fileInput.value = "";
  orig.removeAttribute("src");
  sty.removeAttribute("src");
  originalPreview.removeAttribute("src");
  orig.load();
  sty.load();
  originalPreview.load();
  resetTracking();
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  stage.style.display = "none";
  drop.classList.remove("compact");
  clearWorkflowStage();
  updateWorkflow("reset");
  status("Choose a short video to begin.");
}

btnReset.addEventListener("click", resetProject);
btnCancel.addEventListener("click", () => {
  generationAbortController?.abort();
  stopMedia();
  updateWorkflow("cancelled");
  clearWorkflowStage();
  status("Cancelled. Your uploaded video is still ready.");
});

function drawPoster() {
  orig.currentTime = 0.01;
  orig.onseeked = () => {
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    orig.onseeked = null;
  };
}

async function initLandmarker() {
  status("Loading hand tracker…");
  const fileset = await FilesetResolver.forVisionTasks(WASM_URL);
  landmarker = await HandLandmarker.createFromOptions(fileset, {
    baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" },
    runningMode: "VIDEO",
    numHands: 2,
    minHandDetectionConfidence: 0.3,
    minHandPresenceConfidence: 0.3,
    minTrackingConfidence: 0.3,
  });
  status("Hand tracker ready.");
}

// Dev hook: render one frame at time t (seconds) without realtime playback —
// lets automated tests drive the pipeline in environments that suspend media.
window.__step = (t) =>
  new Promise((resolve) => {
    orig.onseeked = () => {
      orig.onseeked = null;
      ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
      const res = landmarker.detectForVideo(orig, performance.now());
      currentHands = res.landmarks || [];
      updateSelectedTracker(currentHands);
      updatePortalTransition();
      renderPortal(t);
      resolve({
        presence: +presence.toFixed(2),
        corners: corners
          ? corners.map((p) => [Math.round(p.x), Math.round(p.y)])
          : null,
      });
    };
    orig.currentTime = t;
  });

// Dev convenience: ?src=file.mov loads a local file from the dev server.
const srcParam = new URLSearchParams(location.search).get("src");
if (srcParam) {
  fetch(srcParam)
    .then((r) => r.blob())
    .then((b) => loadVideo(new File([b], srcParam, { type: "video/quicktime" })));
}

// ---- AI generation (Gemini Omni Flash video editing, BYOK) ----

const sleep = (ms, signal) => new Promise((resolve, reject) => {
  const timer = setTimeout(resolve, ms);
  signal?.addEventListener("abort", () => {
    clearTimeout(timer);
    reject(new DOMException("Cancelled", "AbortError"));
  }, { once: true });
});

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const fr = new FileReader();
    fr.onload = () => resolve(fr.result.split(",")[1]);
    fr.onerror = reject;
    fr.readAsDataURL(file);
  });
}

async function gemFetch(key, path, init = {}) {
  const res = await fetch(`${GEMINI_BASE}/${path}`, {
    ...init,
    headers: {
      "x-goog-api-key": key,
      ...(init.body ? { "Content-Type": "application/json" } : {}),
      ...(init.headers || {}),
    },
  });
  if (!res.ok) {
    let detail = res.statusText;
    try {
      detail = (await res.json())?.error?.message || detail;
    } catch {}
    throw new Error(`${res.status}: ${detail.slice(0, 160)}`);
  }
  return res.json();
}

// The Interactions API is in preview; be liberal about where the output
// video and status live in the response. Verified live shape: the video is
// in steps[].content[] on the step with type "model_output".
function findOutputVideo(inter) {
  if (inter.output_video) return inter.output_video;
  if (inter.outputVideo) return inter.outputVideo;
  const lists = [inter.outputs, inter.output, inter.content].filter(Array.isArray);
  for (const step of inter.steps || []) {
    if (Array.isArray(step.content)) lists.push(step.content);
  }
  for (const list of lists) {
    const v = list.find(
      (o) => o?.type?.includes?.("video") || o?.video || o?.mime_type?.startsWith?.("video")
    );
    if (v) return v.video || v;
  }
  return null;
}

function isPending(inter) {
  const s = (inter.status || inter.state || "").toLowerCase();
  return ["pending", "in_progress", "processing", "running", "queued"].some((k) =>
    s.includes(k)
  );
}

btnGenerate.addEventListener("click", async () => {
  let generationPrompt;
  try {
    generationPrompt = currentGenerationPrompt();
  } catch (err) {
    promptValidation.textContent = err.message || String(err);
    styleCustom.setAttribute("aria-invalid", "true");
    status("⚠️ " + (err.message || err));
    styleCustom.focus();
    return;
  }
  const key = saveKey();
  if (!key) {
    status("Add your Gemini key above first (or use the placeholder).");
    keyInput.focus();
    return;
  }
  if (!videoFile) return;
  if (videoFile.size > 15 * 1024 * 1024) {
    status("⚠️ Keep the video under ~15MB (a few seconds of 720p) for inline upload.");
    return;
  }
  generationAbortController = new AbortController();
  const { signal } = generationAbortController;
  updateWorkflow("generation_started");
  try {
    setWorkflowStage("Preparing generation");
    status("Preparing generation…");
    const b64 = await fileToBase64(videoFile);

    let referenceImage = null;
    if (referenceImageSelection.file) {
      status("Preparing reference image…");
      try {
        referenceImage = {
          data: await fileToBase64(referenceImageSelection.file),
          mimeType: referenceImageSelection.metadata.mimeType,
        };
      } catch (error) {
        throw new Error(`Reference image preparation failed: ${error.message || error}`);
      }
    }

    setWorkflowStage("Uploading media");
    status("Uploading media to Gemini…");
    let inter = await gemFetch(key, "interactions", {
      method: "POST",
      signal,
      body: JSON.stringify(
        buildGeminiInteractionBody({
          videoData: b64,
          videoMimeType: videoFile.type || "video/mp4",
          prompt: generationPrompt,
          referenceImage,
        }),
      ),
    });
    console.log("interaction response:", inter);

    // Poll the interaction until it settles, if it reports as in-progress.
    const id = inter.id || inter.name;
    let waited = 0;
    setWorkflowStage("Generating AI world");
    while (isPending(inter) && waited < 600) {
      await sleep(5000, signal);
      waited += 5;
      inter = await gemFetch(key, `interactions/${id}`, { signal });
      status(`Generating… (${waited}s, status: ${inter.status || inter.state || "working"})`);
    }

    const vid = findOutputVideo(inter);
    if (!vid) {
      console.error("full response:", inter);
      throw new Error("no video in response — see console for the raw payload");
    }

    status("Processing result…");
    let blob;
    if (vid.data) {
      const bytes = Uint8Array.from(atob(vid.data), (c) => c.charCodeAt(0));
      blob = new Blob([bytes], { type: vid.mime_type || "video/mp4" });
    } else {
      // uri delivery: wait for the file to become ACTIVE, then download.
      let uri = vid.uri || vid.file_uri || vid.url;
      if (!uri) throw new Error("no video data or uri in response");
      const fileName = uri.includes("/files/")
        ? "files/" + uri.split("/files/")[1].split(/[?#]/)[0]
        : uri;
      if (!/^https?:/.test(uri)) uri = `${GEMINI_BASE}/${fileName}:download?alt=media`;
      for (let i = 0; i < 60; i++) {
        const f = await gemFetch(key, fileName, { signal });
        if ((f.state || "").includes("ACTIVE")) break;
        status(`Waiting for the output file… (${(f.state || "processing").toLowerCase()})`);
        await sleep(5000, signal);
      }
      status("Downloading result…");
      const res = await fetch(uri, { headers: { "x-goog-api-key": key }, signal });
      if (!res.ok) throw new Error(`download failed: ${res.status}`);
      blob = await res.blob();
    }

    setWorkflowStage("Finalizing video");
    revokeUrl("stylized");
    stylizedObjectUrl = URL.createObjectURL(blob);
    sty.src = stylizedObjectUrl;
    await waitForMetadata(sty, "Gemini returned a video the browser could not decode.");
    haveAI = true;
    usePlaceholder = false;
    updateWorkflow("generation_finished");
    clearWorkflowStage();
    status("AI video ready — perspective compositing runs during preview or export.");
  } catch (err) {
    console.error(err);
    if (err?.name === "AbortError") {
      updateWorkflow("cancelled");
      clearWorkflowStage();
      status("Generation cancelled. Your uploaded video is still ready.");
      return;
    }
    updateWorkflow("failed");
    status("⚠️ " + friendlyGenerationError(err, !!referenceImageSelection.file));
    clearWorkflowStage();
  } finally {
    generationAbortController = null;
    updateWorkflow("refresh");
  }
});

btnPlaceholder.addEventListener("click", () => {
  if (!videoFile) return;
  usePlaceholder = true;
  haveAI = false;
  updateWorkflow("generation_finished");
  status("Placeholder style active (hue shift) — preview or export, no key needed.");
});

// ---- tracking (ported from finger-frame-effect main.js) ----
function toPixel(lm) {
  return { x: lm.x * canvas.width, y: lm.y * canvas.height };
}
function dist(a, b) {
  return Math.hypot(a.x - b.x, a.y - b.y);
}
function lerpPt(a, b, t) {
  return { x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t };
}
function polygonArea(pts) {
  let a = 0;
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i], q = pts[(i + 1) % pts.length];
    a += p.x * q.y - q.x * p.y;
  }
  return Math.abs(a / 2);
}

function computeQuad(hands) {
  if (hands.length !== 2) return null;
  const info = hands.map((lm) => ({
    index: toPixel(lm[INDEX_TIP]),
    thumb: toPixel(lm[THUMB_TIP]),
    wristX: toPixel(lm[WRIST]).x,
    scale: dist(toPixel(lm[WRIST]), toPixel(lm[MIDDLE_MCP])) + 1,
  }));
  const needed = frameActive ? 0.2 : 0.75;
  for (const hd of info) {
    if (dist(hd.thumb, hd.index) < hd.scale * needed) return null;
  }
  info.sort((a, b) => a.wristX - b.wristX);
  const [A, B] = info;
  const pts = [A.index, B.index, B.thumb, A.thumb];
  const cx = pts.reduce((s, p) => s + p.x, 0) / 4;
  const cy = pts.reduce((s, p) => s + p.y, 0) / 4;
  const hull = [...pts].sort(
    (a, b) => Math.atan2(a.y - cy, a.x - cx) - Math.atan2(b.y - cy, b.x - cx)
  );
  const minArea = frameActive ? 0.0005 : 0.005;
  if (polygonArea(hull) < canvas.width * canvas.height * minArea) return null;
  return pts;
}

function updateTracker(hands) {
  const target = computeQuad(hands);
  if (target) {
    if (!corners) {
      lostFrames = 0;
      frameActive = true;
      jumpFrames = 0;
      corners = target;
      presence = Math.min(1, presence + 0.12);
    } else {
      const moved = target.reduce((s, p, i) => s + dist(p, corners[i]), 0) / 4;
      if (moved > canvas.width * 0.3 && ++jumpFrames < JUMP_CONFIRM_FRAMES) {
        if (++lostFrames > MAX_LOST_FRAMES) presence = Math.max(0, presence - 0.05);
      } else {
        lostFrames = 0;
        frameActive = true;
        jumpFrames = 0;
        const alpha = Math.min(0.85, Math.max(0.35, moved / (canvas.width * 0.05)));
        corners = corners.map((c, i) => lerpPt(c, target[i], alpha));
        presence = Math.min(1, presence + 0.12);
      }
    }
  } else if (corners && ++lostFrames <= MAX_LOST_FRAMES) {
    presence = Math.min(1, presence + 0.12);
  } else {
    presence = Math.max(0, presence - 0.05);
    if (presence === 0) {
      corners = null;
      frameActive = false;
      jumpFrames = 0;
    }
  }
}

function resetTracking() {
  corners = null;
  presence = 0;
  frameActive = false;
  lostFrames = 0;
  jumpFrames = 0;
  trackerState = null;
  stabilizedTracker = TRACKING_MODE === "stabilized"
    ? new StabilizedFrameTracker(canvas.width, canvas.height)
    : null;
  perspectiveCompositor = COMPOSITING_MODE === "legacy"
    ? null
    : new PerspectiveCanvasCompositor(
      canvas.width,
      canvas.height,
      COMPOSITING_MODE === "perspective_occlusion",
      parallaxEnabled,
    );
  portalCrossingController = portalCrossingEnabled && COMPOSITING_MODE !== "legacy"
    ? new PortalCrossingController(
        canvas.width,
        canvas.height,
        PORTAL_CROSSING_CONFIG,
        {
          stylePreset: styleSelect.value,
          customPromptPresent: !!styleCustom.value.trim(),
          referenceImagePresent: !!referenceImageSelection.file,
        },
      )
    : null;
  portalTransition = Object.freeze({
    state: TransitionState.INACTIVE,
    coverage: 0,
    progress: 0,
    confidence: 0,
    expandedQuad: null,
    portalId: null,
  });
  currentHands = [];
}

function updateSelectedTracker(hands) {
  if (TRACKING_MODE === "legacy") {
    updateTracker(hands);
    trackerState = {
      rawQuad: computeQuad(hands),
      stabilizedQuad: corners,
      confidence: presence,
      detectionState: corners ? "legacy" : "lost",
      isPredicted: false,
      dropoutFrames: lostFrames,
    };
    return trackerState;
  }
  if (!stabilizedTracker) {
    stabilizedTracker = new StabilizedFrameTracker(canvas.width, canvas.height);
  }
  const rawQuad = computeQuad(hands);
  trackerState = stabilizedTracker.update(rawQuad);
  corners = trackerState.stabilizedQuad;
  presence = trackerState.confidence;
  frameActive = stabilizedTracker.active;
  lostFrames = trackerState.dropoutFrames;
  return trackerState;
}

function updatePortalTransition() {
  if (!portalCrossingController) {
    portalTransition = Object.freeze({
      state: corners ? TransitionState.PORTAL_VISIBLE : TransitionState.INACTIVE,
      coverage: 0,
      progress: 0,
      confidence: presence,
      expandedQuad: corners,
      portalId: null,
    });
    return portalTransition;
  }
  portalCrossingController.setGenerationMetadata({
    stylePreset: styleSelect.value,
    customPromptPresent: !!styleCustom.value.trim(),
    referenceImagePresent: !!referenceImageSelection.file,
  });
  portalTransition = portalCrossingController.update({
    quad: corners,
    confidence: trackerState?.confidence || 0,
    detectionState: trackerState?.detectionState || "invalid",
    forceProgress: FORCED_TRANSITION_PROGRESS,
  });
  return portalTransition;
}

// ---- rendering ----
function quadPath(q) {
  ctx.beginPath();
  ctx.moveTo(q[0].x, q[0].y);
  for (let i = 1; i < 4; i++) ctx.lineTo(q[i].x, q[i].y);
  ctx.closePath();
}

function drawWindow(q) {
  ctx.save();
  quadPath(q);
  ctx.clip();
  ctx.globalAlpha = presence;
  if (haveAI) {
    ctx.drawImage(sty, 0, 0, canvas.width, canvas.height);
  } else {
    ctx.filter = "hue-rotate(140deg) saturate(1.7) contrast(1.15)";
    ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);
    ctx.filter = "none";
  }
  ctx.restore();
  ctx.globalAlpha = 1;
}

function drawOutline(q, t) {
  ctx.save();
  ctx.globalAlpha = presence;
  quadPath(q);
  ctx.setLineDash([10, 8]);
  ctx.lineDashOffset = -t * 40;
  ctx.lineWidth = 2;
  ctx.strokeStyle = "rgba(255,255,255,0.95)";
  ctx.shadowColor = "rgba(0,0,0,0.5)";
  ctx.shadowBlur = 6;
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.lineDashOffset = 0;
  ctx.shadowBlur = 0;
  q.forEach((p, i) => {
    const r = 7 + Math.sin(t * 3 + i * 1.5) * 1.5;
    const halo = (t * 0.8 + i * 0.25) % 1;
    ctx.beginPath();
    ctx.arc(p.x, p.y, r + halo * 14, 0, Math.PI * 2);
    ctx.strokeStyle = `rgba(255,255,255,${0.5 * (1 - halo) * presence})`;
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.fillStyle = "#fff";
    ctx.fill();
    ctx.beginPath();
    ctx.arc(p.x, p.y, r, 0, Math.PI * 2);
    ctx.strokeStyle = "rgba(0,0,0,0.25)";
    ctx.lineWidth = 1.5;
    ctx.stroke();
  });
  ctx.restore();
}

function renderPortal(t) {
  const renderQuad = portalCrossingEnabled
    ? portalTransition.expandedQuad
    : corners;
  const isFullAI = portalTransition.state === TransitionState.FULL_AI;
  if (!renderQuad || (!isFullAI && presence <= 0.01)) return;
  if (COMPOSITING_MODE === "legacy") {
    drawWindow(renderQuad);
    drawOutline(renderQuad, t);
  } else {
    perspectiveCompositor.draw({
      context: ctx,
      portalSource: haveAI ? sty : orig,
      originalSource: orig,
      quad: renderQuad,
      motionQuad: corners,
      hands: currentHands,
      trackerState,
      filter: haveAI ? "none" : "hue-rotate(140deg) saturate(1.7) contrast(1.15)",
      transitionProgress: portalTransition.progress,
    });
  }
}

let lastVideoTime = -1;
function loop() {
  if (!orig.paused && !orig.ended) requestAnimationFrame(loop);

  ctx.drawImage(orig, 0, 0, canvas.width, canvas.height);

  if (landmarker && orig.currentTime !== lastVideoTime) {
    lastVideoTime = orig.currentTime;
    const res = landmarker.detectForVideo(orig, performance.now());
    currentHands = res.landmarks || [];
    updateSelectedTracker(currentHands);
    updatePortalTransition();
  }

  // Keep the stylized video in step with the original.
  if (haveAI && Math.abs(sty.currentTime - orig.currentTime) > 0.15) {
    sty.currentTime = orig.currentTime;
  }

  renderPortal(orig.currentTime);
}

async function playThrough() {
  resetTracking();
  orig.currentTime = 0;
  if (haveAI) {
    sty.currentTime = 0;
    sty.play();
  }
  await orig.play();
  requestAnimationFrame(loop);
}

btnPlay.addEventListener("click", () => {
  if (exporting) return;
  updateWorkflow("preview_started");
  setWorkflowStage("Tracking hand frame");
  status("Previewing the tracked portal…");
  let built = false;
  const previewProgress = () => {
    if (!built && corners) {
      built = true;
      setWorkflowStage("Building portal");
      requestAnimationFrame(() => setWorkflowStage("Rendering transition"));
    }
  };
  orig.addEventListener("timeupdate", previewProgress);
  orig.addEventListener("ended", () => {
    orig.removeEventListener("timeupdate", previewProgress);
    clearWorkflowStage();
    updateWorkflow("preview_finished");
    status("Preview complete. Download when you are ready.");
  }, { once: true });
  playThrough().catch((error) => {
    console.error("Preview failed", error);
    clearWorkflowStage();
    updateWorkflow("failed");
    status(`Preview failed: ${error.message || error}`);
  });
});

// ---- export (canvas capture -> webm download) ----
btnExport.addEventListener("click", async () => {
  if (exporting) return;
  exporting = true;
  generationAbortController = new AbortController();
  const { signal } = generationAbortController;
  updateWorkflow("export_started");
  setWorkflowStage("Tracking hand frame", "export pass");
  status("Rendering the final video…");

  const stream = canvas.captureStream(30);
  const sourceStream = orig.captureStream?.() || orig.mozCaptureStream?.();
  for (const track of sourceStream?.getAudioTracks?.() || []) stream.addTrack(track);
  // Prefer MP4 where the browser can record it (Safari, newer Chrome);
  // fall back to WebM elsewhere.
  const mime = [
    "video/mp4;codecs=avc1.42E01E",
    "video/mp4",
    "video/webm;codecs=vp9",
    "video/webm",
  ].find((m) => MediaRecorder.isTypeSupported(m)) || "video/webm";
  const isMp4 = mime.startsWith("video/mp4");
  try {
    recorder = new MediaRecorder(stream, {
      mimeType: mime,
      videoBitsPerSecond: 10_000_000,
    });
    const chunks = [];
    recorder.ondataavailable = (e) => e.data.size && chunks.push(e.data);
    const finished = new Promise((resolve, reject) => {
      recorder.onerror = () => reject(new Error("The browser recorder could not encode the output."));
      recorder.onstop = resolve;
    });
    orig.onended = () => {
      orig.onended = null;
      setWorkflowStage("Restoring audio");
      if (recorder?.state === "recording") recorder.stop();
    };
    recorder.start(1000);
    await playThrough();
    await finished;
    if (signal.aborted) return;
    setWorkflowStage("Finalizing video");
    const ext = isMp4 ? "mp4" : "webm";
    const blob = new Blob(chunks, { type: isMp4 ? "video/mp4" : "video/webm" });
    revokeUrl("export");
    exportObjectUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = exportObjectUrl;
    a.download = `finger-frame-ai-output.${ext}`;
    a.click();
    status(
      `Exported finger-frame-ai-output.${ext}.` +
      (isMp4 ? "" : " This browser supports WebM recording; use the offline MP4 path for a guaranteed MP4.")
    );
    updateWorkflow("export_finished");
  } catch (error) {
    console.error("Output rendering failed", error);
    if (!signal.aborted) {
      updateWorkflow("failed");
      status(`Output rendering failed: ${error.message || error}`);
    }
  } finally {
    for (const track of stream.getTracks()) track.stop();
    for (const track of sourceStream?.getTracks?.() || []) track.stop();
    recorder = null;
    exporting = false;
    generationAbortController = null;
    clearWorkflowStage();
    updateWorkflow(signal.aborted ? "cancelled" : "refresh");
  }
});

updateWorkflow("reset");
